### ISSUE TITLE
Create a base template
Bootstrap - Sass - Grunt

### ISSUE THREAD

**Issue by dashiwa** [dashiwa/aggregator#1]

**Comment by dashiwa** [comment]
Hi @dwayneHicks please create a template
Use the bootstrap Grunt and SASS

**Comment by DwayneHicks** [comment]
ok Dashiva, I'm Chuck Norris front-end developments's!

**Comment by dashiwa** [comment]
@DwayneHicks I am not see your Pull request. Please create again

**Comment by dashiwa** [comment]
Hi @DwayneHicks Sorry for delay.
Please use this destination branch - release/OS-1.0-dev
Could you please review my PR  - https://github.com/dashiwa/aggregator/pull/9?
After the merger. Create a branch in the format feature/AGG-0X. Use your code.
And create a new PR 
Thanks Raman;
